- .gitignore
IntelliJ idea config files rule is not present on gitignore. This might be also on the skeleton-app repo.
-
-
> Add IntelliJ project files to gititnore

- cypress/integration/landing-page.spec.js
- i18n/en.pot
- package.json
- src/components/app/LandingPage.jsx
- src/components/app/Root.jsx
- src/index.js
- yarn.lock
* **Issue:** Closes #3
- Routes to sync pages follow "dhisEndpoint-sync" to potentially make the sync pages re-usable when possible with the endpoint as identifier.
- Removed feedback tool from Root following vaccination-app.
- Implemented a basic cypress test that validates the 7 pages are in the landing page
> Implement basic landing page

- package.json
- src/models/dataStore.js
- yarn.lock
- Pagination now works as expected
> Update d2-ui-components to 0.0.9

- .prettierignore
- cypress/support/commands.js
- i18n/en.pot
- src/components/app/LandingPage.jsx
- src/components/instance-configurator/InstanceConfigurator.jsx
- src/components/instance-form-builder/GeneralInfoForm.jsx
- src/components/instance-form-builder/InstanceFormBuilder.jsx
- src/components/instance-form-builder/SaveButton.jsx
- src/components/shared/PageHeader.jsx
- src/components/sync-configurator/BaseSyncConfigurator.jsx
- src/components/sync-configurator/DataElementSync.jsx
- src/components/sync-configurator/IndicatorSync.jsx
- src/components/sync-configurator/OrganisationUnitSync.jsx
- src/components/sync-configurator/ValidationRuleSync.jsx
- src/models/d2Model.ts
- src/models/dataStore.ts
- src/models/instance.ts
- src/react-app.d.ts
- src/types/d2.d.ts
* **Issue:** Closes several issues of #7 
-
I was going to add a help text but since I'm not completely familiar with the use-case of this app it would probably need changing. We need to define it and I'll update it.
- Both in this app and in vaccination we are having a bit of an issue with the spacing on the top of the objectsTable, is it worth it to modify it in the d2-ui library?
> Several cosmetic changes

- i18n/en.pot
- src/components/instance-configurator/InstanceConfigurator.jsx
This PR is based against PR #27
> Add confirmation dialog to delete instance action

- src/models/dataStore.ts
- src/models/instance.ts
It's not a ticket but something we discussed that might be good to do
This PR is based against PR #27
> Separate instances model and dataStore

- src/components/instance-form-builder/GeneralInfoForm.jsx
- src/models/instance.ts
- src/types/modules.d.ts
Thanks to @tokland for the code snippet!
This PR is based against PR #27
> Add instance connection test to save

- i18n/en.pot
- src/models/d2Model.ts
- src/utils/d2.ts
* **Issue:** Closes #43 
- Add custom columns/details for OU
- The abstract model handles the logic behind to add the columns, order, list...
- Branch based on top of #37 to minimize conflicts. Should be merged afterwards.
> Add level to OU ObjectsTable

- src/components/app/Root.jsx
- src/components/instance-configurator/InstanceConfigurator.jsx
- src/components/instance-form-builder/InstanceFormBuilder.jsx
- src/models/instance.ts
* **Issue:** Closes #29
Included instance id on url and perform the instance get on page refresh
> Add instance id to edit instance url, reload instance on page refresh

- src/components/app/Root.jsx
- src/components/sync-dialog/SyncDialog.jsx
- src/logic/synchronization.ts
- src/models/d2Model.ts
- src/types/synchronization.d.ts
- src/utils/d2.ts
- src/utils/synchronization.ts
* **Issue:** Closes #55 
- Use lodash to parse nested rules.
- GroupSets are now properly included in the metadata package.
> Refactor Nested Rules

- src/models/d2Model.ts
- yarn.lock
- If input text in search field is a Valid UID, search for it instead of searching by displayName
- Multiple filter queries are not supported by DHIS2 as far as I know
- This "hidden" feature might be helpful for us and also advanced users of the app. I don't foresee any issue of implementing this utility.
> Allow users to find by id with match case

- i18n/en.pot
- src/components/sync-configurator/BaseSyncConfigurator.jsx
- src/components/sync-configurator/IndicatorSync.jsx
- src/components/sync-configurator/OrganisationUnitSync.jsx
- src/components/sync-configurator/ValidationRuleSync.jsx
- src/models/d2Model.ts
- src/types/d2-ui-components.d.ts
* **Issue:** Closes #65 and Closes #66 
- Abstract group and level filters
- Add filters for Validation Rules
- Add filters for Indicators
- Refactor Organisation Unit filters
- Memoization is gone in this PR, I'm not sure where we should place it in the state.
> Add filters for Indicators and ValidationRules

- i18n/en.pot
- package.json
- src/components/app/App.css
- src/components/app/App.jsx
- src/index.js
- yarn.lock
- We're back using default v30 header bar with translations fixed.
- In the future we might migrate to the new [@dhis2/ui-widgets](https://github.com/dhis2/ui-widgets) HeaderBar but the style is v32.
> Move back to v30 header-bar

- src/models/d2Model.ts
- src/utils/d2.ts
* **Issue:** Closes #10 
- Include legendSets
- Include indicatorType
- Include indicatorGroups (do not include the children indicators)
- Include indicatorGroupSets (weird behavior of DHIS2 API)
```json
{
"indicators": [
{
"code": "ADO_PR",
"lastUpdated": "2018-08-17T04:00:28.157",
"id": "d4wQQ1vaIF2",
"created": "2018-02-20T14:11:27.208",
"name": "Adolescent programme reporting rate",
"shortName": "Adolescent programme reporting rate",
"displayName": "Adolescent programme reporting rate",
"publicAccess": "r-------",
"description": "Adolescent programme reporting rate is calculated using 'Delivery 10-14 years in facility' as a proxy element evaluating whether an element is reported in this month compared to a value exist in the previous 3 months",
"displayShortName": "Adolescent …
```
> Basic Indicator Sync Rules

- src/models/d2Model.ts
* **Issue:** Closes #11 
* **Status:** Tested with Validation Rule with a group and attributes set to both of them.
- Include attributes
- Include validationRuleGroups (with attributes and do not include the child validation rules)
```json
{
"validationRules": [
{
"code": "test01",
"lastUpdated": "2019-04-26T12:23:12.736",
"id": "SF7fBhU8jDw",
"created": "2019-04-26T12:18:05.470",
"name": "Test01",
"importance": "MEDIUM",
"displayName": "Test01",
"publicAccess": "rw------",
"operator": "not_equal_to",
"externalAccess": false,
"dimensionItem": "SF7fBhU8jDw",
"periodType": "Monthly",
"skipFormValidation": false,
"favorite": false,
"access": {
"read": true,
"update": true,
"externalize": true,
"delete": true,
"write": true,
"manage": true
},
"leftSide": {
"expression": …
```
> Basic Validation Rules Sync

- cypress/integration/instance-configurator.spec.js
- cypress/integration/landing-page.spec.js
- cypress/support/commands.js
- cypress/support/network-fixtures.js
- cypress/support/utils.js
- src/components/instance-form-builder/GeneralInfoForm.jsx
- src/components/shared/PageHeader.jsx
* **Issue:** Closes #4 
* **Status:** Very early stage, not ready to merge
- Landing Page now verifies it can open all the pages correctly.
- Instance Configuration deletes all the existing Instances and creates three new Instances: [STILL WIP]
- Valid Instance
- Wrong Endpoint
- Valid Instance with wrong user privileges
> Add Integration tests for Instance creation and metadata synchronization

- i18n/en.pot
- package.json
- yarn.lock
- Move i18n to our fork
- Update strings
> Update dependencies for i18n and d2-ui-components

- i18n/en.pot
- src/models/d2Model.ts
- src/models/instance.ts
* **Issue:** Closes #36 
- Add new case for Not Found
- Remove trailing slashes
- Make sure all invalid scenarios are tested
> Improve instance test connection

- package.json
- src/components/sync-summary/SyncSummary.jsx
- src/models/d2Model.ts
- src/utils/synchronization.ts
> hotfix: Disable atomic

- src/models/dataStore.ts
* **Issue:** Work on #39 
- Asume namespace and dataStore exist and detect 404 errors
> Reduce network calls of dataStore

- src/models/d2Model.ts
- src/utils/synchronization.ts
* **Issue:** Closes #74 
- Include group/groupSet assignments on metadata package
- Disable atomic and try to import even if the references are not matched by destination instance
> Include group assignments and disable atomic

- package.json
- src/components/instance-configurator/InstanceConfigurator.jsx
- src/components/notifications-table/NotificationsTable.jsx
- src/components/sync-configurator/BaseSyncConfigurator.jsx
- yarn.lock
* **Issue:** Closes #88 
- Remove our own FAB
- Re-use the ObjectsTable new button
- Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)?
See https://github.com/EyeSeeTea/d2-ui-components/pull/37
> Move Sync button to ObjectsTable

- package.json
- public/manifest.json
- Update public html manifest
- Update npm description
- Update DHIS2 manifest
- Renaming the app in DHIS2 manifest forces a duplicate application on the instance, we should change it before the next milestone release to the correct final naming.
> Update manifest name

- src/components/notifications-table/NotificationsTable.jsx
- Sort notifications from newer to older
> Sort notifications starting with the most recent

- src/components/sync-configurator/DataElementSync.jsx
- src/models/d2Model.ts
- src/utils/d2.ts
* **Issue:** Closes #9 
- Added data element group dropdown
- Support for recursive metadata fetching of data elements
<details><summary>Example</summary>
<p>
```json
{
"dataElements": [{
"code": "test01",
"lastUpdated": "2019-06-07T12:49:18.337",
"id": "Xl0Va10Yi4G",
"created": "2019-06-07T12:49:18.337",
"name": "Test",
"shortName": "test01",
"aggregationType": "NONE",
"domainType": "AGGREGATE",
"displayName": "Test",
"publicAccess": "rw------",
"displayShortName": "test01",
"externalAccess": false,
"valueType": "TEXT",
"dimensionItem": "Xl0Va10Yi4G",
"displayFormName": "Test",
"zeroIsSignificant": false,
"favorite": false,
"optionSetValue": true,
"dimensionItemType": "DATA_ELEMENT",
"access": {
"read": true,
"update": true,
"externalize": true,
"delete": true,
"write": true,
"manage": …
```
> Basic support for dataElements

- i18n/en.pot
- src/components/instance-creation-page/GeneralInfoForm.jsx
- src/components/rules-creation-page/steps/GeneralInfoStep.jsx
- src/components/rules-list-page/SyncRulesPage.jsx
* **Issue:** Closes #119 
- Add asterisks programatically in i18n strings
- Make target instances a csv in Sync Rules
- Make default action to be edit
> Sync rules improvements

- src/components/metadata-table/MetadataTable.jsx
- src/components/rules-creation-page/SyncRulesWizard.jsx
- src/components/rules-creation-page/steps/MetadataSelectionStep.jsx
- src/components/rules-creation-page/steps/SaveStep.jsx
- src/components/sync-dialog/SyncDialog.jsx
- src/components/synchronization-page/DataElementPage.jsx
- src/components/synchronization-page/GenericSynchronizationPage.jsx
- src/components/synchronization-page/IndicatorPage.jsx
- src/components/synchronization-page/OrganisationUnitPage.jsx
- src/components/synchronization-page/ValidationRulePage.jsx
- src/logic/synchronization.ts
- src/models/d2Model.ts
- src/models/d2ModelFactory.ts
- src/models/syncRule.ts
- src/types/synchronization.d.ts
- src/utils/d2.ts
* **Issue:** Closes #123 
- Add Groups and GroupSets where applicable for DE, I and VR
> Add group and groupsets metadata types

- i18n/en.pot
- package.json
- src/components/app/App.css
- src/components/app/App.jsx
- src/index.js
- yarn.lock
* **Issue:** Closes #78 
- Use again the now finished header bar
- All the previous issues they had appear to be solved now
- Tested on both localhost and production
> [Header] Upgrade to ui-widgets header bar

- .gitignore
- .travis.yml
- src/types/modules.d.ts
- Update gitignore with common ignored files
- Update modules type definition to include d2.init
- Update gitignore with common ignored files
- Update syncRules model to reflect the changes to ```enabled``` property
- Update syncRules model to reflect the new filters for ```list``` method
- Update the type definitions files
Related PRs:
- https://github.com/EyeSeeTea/metadata-synchronization/pull/136
- https://github.com/EyeSeeTea/metadata-synchronization-server/pull/5
> [Refactor] Updates from server app

- src/models/d2ModelFactory.ts
- Fixes small issue with includeRules nesting
> Add missing imports for d2ModelFactory

- README.md
* **Issue:** Closes #187
Rename REACT_APP_DHIS2_URL to REACT_APP_DHIS2_BASE_URL
> Rename REACT_APP_DHIS2_URL to REACT_APP_DHIS2_BASE_URL

- .travis.yml
> Update travis to use next node LTS

- src/models/syncRule.ts
- yarn.lock
* **Issue:** Closes #201 
- Query all, filter and then create pager
- This needs to be ported to ``development-malaria``, does not happen in ``development`` because it was introduced with the sharing settings filtering feature.
- This change does not follow DRY as we have similar code also in the dataStore main class. However since all that code will be migrated to ``d2-api`` soon, the way we paginate over results and do the filters will completely change. At least we have it now working so WHO is able to use the app while we refactor this code with our new vision.
> Fix bug with filtered objects not properly loading paginated

- src/logic/metadata.ts
- src/models/d2Model.ts
- src/models/deletedObjects.ts
- src/models/syncRule.ts
- src/utils/permissions.ts
- src/utils/testing.js
- yarn.lock
> Merging development who changes

- src/logic/delete.ts
- src/logic/synchronization.ts
- src/models/instance.ts
* **Issue:** Closes #211 
- Add ``toObject()`` wrapper that removes password from object
- Remove an unused ``await`` on save()
> [Bugfix] Do not leak password on debug messages

- src/components/sync-summary/SyncSummary.jsx
- src/types/d2.d.ts
- src/utils/synchronization.ts
* **Issue:** Closes #212 
- Add a new optional message prop that prints the error from DHIS2
> [Bugfix] Add better error handling and print message from dhis

- src/models/d2Model.ts
- Add options with optionSets in dataElements
> [Bugfix] Include options with optionSets

- i18n/en.pot
- src/components/d2-objects-table/D2ObjectsTable.tsx
- src/components/dropdown/Dropdown.jsx
- src/components/sync-wizard/common/SchedulerStep.jsx
- src/components/sync-wizard/data/EventsSelectionStep.tsx
* **Issue:** Closes #255 
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/24
- Improve scheduler step behavior for dropdown and auto-enabled
- Set rows per page to 25
> [Feature] Improve scheduler step

- src/components/sync-wizard/SyncWizard.tsx
- src/pages/sync-rules-creation/SyncRulesCreationPage.tsx
* **Issue:** Closes #262 
- Make steps clickable
- Add validation to previous steps instead of current one
- There're multiple scenarios that might need to be adapted after this change (specially for on-demand sync).
> [Feature] Make wizard steps clickable

- src/components/d2-objects-table/D2ObjectsTable.tsx
* **Issue:** Closes #251 
- Calculate ids when search term is provided
> [Bugfix] Fix select in all pages with search box

- i18n/en.pot
- package.json
- src/components/sync-wizard/data/CategoryOptionsSelectionStep.tsx
- src/components/sync-wizard/data/EventsSelectionStep.tsx
- src/logic/delete.ts
- src/logic/sync/generic.ts
- src/types/d2.d.ts
- src/types/synchronization.d.ts
- src/utils/synchronization.ts
- yarn.lock
* **Issue:** Closes #297
* **Issue:** Closes #298
- Unify "OK" and "Success" -> "Success" for metadata, aggregated and events
- Add loading spinner to "Events" selection step
- On Edit category options do not show up properly selected
> [Feature] Misc updates

- .travis.yml
> use docker for testing

- package.json
- src/components/sync-wizard/common/SchedulerStep.jsx
- src/components/sync-wizard/common/SummaryStep.jsx
- src/components/sync-wizard/data/EventsSelectionStep.tsx
- src/logic/sync/generic.ts
- src/models/syncRule.ts
- src/pages/sync-on-demand/SyncOnDemandPage.tsx
- src/pages/sync-rules-list/SyncRulesListPage.jsx
- src/utils/synchronization.ts
- yarn.lock
* **Issue:** Closes #305
* **Issue:** Closes #306
* **Issue:** Closes #308 
- Move JSON download to a new utils file
- Prepend sync rule name using lowercase kebab-case ``foo-bar-sync-date``.
- Rename internal "on-demand" name to "manual" so when downloading a file it looks like ``manual-aggregated-sync-date``.
- Change all cron expressions to be ran during midnight by default.
- Add moment wrapper for data sync rule start and end dates
> [Feature] Misc changes for user feedback

- i18n/en.pot
- package.json
- src/components/mapping-dialog/MappingDialog.tsx
- src/components/metadata-table/MetadataTable.tsx
- src/logic/sync/aggregated.ts
- src/logic/sync/events.ts
- src/logic/sync/generic.ts
- src/logic/sync/metadata.ts
- src/models/d2Model.ts
- src/pages/instance-mapping/InstanceMapping.tsx
- yarn.lock
* **Issue:** Closes #160 
* **Issue:** Closes #161 
* **Issue:** Closes #162 
- Add logic to map DE, OU and COC
- Mapping support for events is limited (dataElements only). We need support for "programs" and "programStages" before fully working.
> [Feature] Add metadata mapping logic

- i18n/en.pot
- src/components/sync-summary/SyncSummary.jsx
- src/logic/sync/aggregated.ts
- src/models/syncReport.ts
- src/pages/history/HistoryPage.tsx
- src/pages/instance-mapping/InstanceMapping.tsx
- src/pages/sync-on-demand/SyncOnDemandPage.tsx
- src/pages/sync-rules-list/SyncRulesListPage.tsx
> [Feature] Add disabled state and fix bug with summary

- i18n/en.pot
- src/pages/history/HistoryPage.tsx
- src/pages/sync-rules-list/SyncRulesListPage.tsx
> [Fix] Issues found during testing

- package.json
- src/components/mapping-dialog/MappingDialog.tsx
- src/components/sync-wizard/data/OrganisationUnitsSelectionStep.tsx
- yarn.lock
- Add initially expanded prop to OrgUnitSelector components
> [Feature] Final misc fixes for the release

- i18n/en.pot
- package.json
- src/components/mapping-dialog/MappingDialog.tsx
- src/components/mapping-table/MappingTable.tsx
- src/components/mapping-table/utils.tsx
- src/components/mapping-wizard/MappingWizard.tsx
- src/components/mapping-wizard/Steps.tsx
- src/components/metadata-table/MetadataTable.tsx
- src/components/metadata-table/utils.tsx
- src/logic/sync/aggregated.ts
- src/logic/sync/events.ts
- src/models/d2Model.ts
- src/models/d2ModelFactory.ts
- src/pages/instance-mapping/InstanceMappingLandingPage.tsx
- src/pages/instance-mapping/InstanceMappingPage.tsx
- src/types/d2.d.ts
- src/types/synchronization.d.ts
- src/utils/d2.ts
- src/utils/synchronization.ts
- yarn.lock
* **Issue:** Closes #379 
* **Issue:** Closes #389 
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/43
- Update UI to reflect new programs -> programStages -> dataElements relation
- Update logic to map events data
- Fix error 500 with OU on WHO servers
- Enable bulk action for "Set mapping" contextual action
- There're known errors with TableSelection and children rows.
> [Feature] Refactor mapping for events data

- src/models/__tests__/syncRule.spec.ts
> Fix jest tests

- i18n/en.pot
- src/components/mapping-table/MappingTable.tsx
- src/components/mapping-table/utils.tsx
- src/components/mapping-wizard/MappingWizard.tsx
- src/logic/sync/events.ts
- src/models/dataStore.ts
- src/pages/app/App.jsx
- src/pages/sync-rules-list/SyncRulesListPage.tsx
- src/utils/dataStore.ts
* **Issue:** Closes #445
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/54
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/55
-
To be revisited in the future:
- We don't show "Conflict" icon if item was removed, we just reset the mapping.
- We don't remove item if it has been "un-assigned"
> [Feature] Last changes for release

- i18n/en.pot
- src/components/mapping-dialog/MappingDialog.tsx
- src/components/mapping-table/utils.tsx
- src/pages/instance-mapping/InstanceMappingLandingPage.tsx
- src/pages/instance-mapping/InstanceMappingPage.tsx
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/53
-
> [Fix] Add instance name to mapping dialog title

- package.json
- src/logic/sync/aggregated.ts
- src/types/synchronization.d.ts
- src/utils/synchronization.ts
> [Fix] Map attribute option combos

- .eslintrc.js
- src/components/mapping-table/MappingTable.tsx
- src/components/mapping-table/utils.tsx
- src/components/mapping-wizard/MappingWizard.tsx
- src/components/metadata-table/MetadataTable.tsx
- src/logic/sync/aggregated.ts
- src/models/dhis/mapping.ts
- src/types/synchronization.d.ts
- src/utils/synchronization.ts
> [Fix] Add category id during item mapping

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/domain/aggregated/usecases/AggregatedSyncUseCase.ts
- src/domain/events/usecases/EventsSyncUseCase.ts
- src/domain/metadata/usecases/DeletedMetadataSyncUseCase.ts
- src/domain/metadata/usecases/MetadataSyncUseCase.ts
- src/domain/notifications/usecases/ImportPullRequestUseCase.ts
- src/domain/synchronization/entities/SynchronizationResult.ts
- src/domain/synchronization/usecases/GenericSyncUseCase.ts
- src/presentation/common/components/module-package-list-table/ModulePackageListTable.tsx
- src/presentation/common/components/package-list-table/PackageListTable.tsx
- src/presentation/webapp/components/packages-diff-dialog/PackagesDiffDialog.tsx
- src/presentation/webapp/components/packages-diff-dialog/utils.ts
- src/presentation/webapp/components/sync-summary/SyncSummary.tsx
- src/presentation/webapp/pages/module-package-list/ModulePackageListPage.tsx
- Add back lost functionality (showing sync summary on modules/packages list)
- Add origin instance to sync report when available
> [Feature] Misc changes

- package.json
- yarn.lock
-   **Issue:** Closes #593 
- https://github.com/EyeSeeTea/d2-ui-components/pull/173
- Refactor `d2-ui-components formatting -> defaultFormatter`.
> Refine parsing of instance name for date-like names

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/domain/modules/entities/Module.ts
- src/domain/modules/usecases/ListModulesUseCase.ts
- src/domain/packages/entities/Package.ts
- src/domain/packages/usecases/ListPackagesUseCase.ts
- src/presentation/common/components/module-list-table/ModuleListTable.tsx
- src/presentation/common/components/package-list-table/PackageListTable.tsx
- src/presentation/webapp/components/dropdown/Dropdown.tsx
- src/presentation/webapp/components/module-wizard/ModuleWizard.tsx
- src/presentation/webapp/components/module-wizard/Steps.ts
- src/presentation/webapp/components/module-wizard/common/GeneralInfoStep.tsx
- src/presentation/webapp/pages/home/HomePage.tsx
- src/presentation/webapp/pages/modules-creation/ModuleCreationPage.tsx
-   **Issue:** Closes #561 
- Disable department change on module edit
- Show package listing to app executors on landing page
- Add sharing settings for modules and respect package listing depending on its module
> [Feature] Update permissions modules

- src/models/dhis/metadata.ts
- http://who-dev.essi.upc.edu:8083/issues/3575
- Add missing dependency
> [Fix] Add data entry form dependency to tracker programs

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/domain/modules/entities/Module.ts
- src/domain/modules/usecases/SaveModuleUseCase.ts
- src/presentation/common/components/module-list-table/ModuleListTable.tsx
- src/presentation/webapp/components/module-wizard/common/GeneralInfoStep.tsx
> [Fix] Mark department as mandatory and show department on sharign settings dialog

- src/domain/common/entities/Validations.ts
-   **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/73
> [Fix] Add localhost validation to field

- src/domain/metadata/usecases/MetadataSyncUseCase.ts
- src/models/dhis/metadata.ts
- src/utils/__tests__/expressionParser.spec.ts
- src/utils/expressionParser.ts
-   **Issue:** Closes #626 
- Add support to map ``expression`` and ``filter``
- Add support for logical operators
> [Fix] Add program indicator expression mapping

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/domain/synchronization/usecases/GenericSyncUseCase.ts
- src/domain/synchronization/usecases/PrepareSyncUseCase.ts
- src/presentation/react/components/module-list-table/ModuleListTable.tsx
- src/presentation/webapp/pages/manual-sync/ManualSyncPage.tsx
- src/presentation/webapp/pages/sync-rules-list/SyncRulesListPage.tsx
- src/scheduler/scheduler.ts
> [Fix] Add error handling for instances not found or down

- package.json
- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/data/events/EventsD2ApiRepository.ts
- src/data/metadata/MetadataD2ApiRepository.ts
- src/domain/instance/usecases/ValidateInstanceUseCase.ts
- yarn.lock
-   **Issue:** Closes #620 
- Update error message handling
> [Feature] Update error messages

- src/data/packages/GitHubOctokitRepository.ts
- src/data/storage/DownloadWebRepository.ts
- src/domain/packages/repositories/GitHubRepository.ts
- src/domain/packages/usecases/DiffPackageUseCase.ts
- src/domain/packages/usecases/DownloadPackageUseCase.ts
- src/domain/packages/usecases/GetStorePackageUseCase.ts
- src/domain/packages/usecases/ImportPackageUseCase.ts
- src/domain/packages/usecases/ListStorePackagesUseCase.ts
- src/domain/storage/repositories/DownloadRepository.ts
- src/presentation/react/components/package-import-dialog/PackageImportDialog.tsx
- src/presentation/react/components/package-list-table/PackageListTable.tsx
-   **Issue:** Closes #679
-   **Issue:** Closes #680
- Refactor github blob file calls to use authenticated request
- Fix coc mapping on DHIS2 instances
> [Feature] Misc fixes after release

- src/domain/packages/entities/Package.ts
- src/presentation/react/components/package-list-table/PackageListTable.tsx
-   **Issue:** Closes #683
-   **Issue:** Closes #684
-   **Issue:** Closes #685
-
> [Fix] Minor issues Vol. 1

- src/domain/packages/usecases/PublishStorePackageUseCase.ts
- src/presentation/react/components/metadata-table/MetadataTable.tsx
- src/presentation/react/components/package-list-table/PackageListTable.tsx
-   **Issue:** Closes #685
-   **Issue:** Closes #688
-
> [Fix] Minor changes Vol. 2

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/presentation/react/components/package-import-wizard/steps/PackageMappingStep.tsx
-   **Issue:** Closes #698 
- Compare current mapping ids against package contents ids in level 1 to show warnings 
The warning is calculated to enter in the step and re-calculated on every mapping change
> Show warnings in mapping step in package import wizard

- config/testSetup.js
- package.json
- yarn.lock
> [Fix] Solve latin1 encoding on scheduler

- src/data/transformations/TransformationD2ApiRepository.ts
-   **Issue:** Closes #762 
- Add transformation cleaner to avoid bugs generating package payload from a module
> Add transformation cleaner

- src/presentation/react/components/module-wizard/common/MetadataSelectionStep.tsx
-   **Issue:** Closes #763
- Add ``programRule`` model to module creation wizard
> [Feature] Add program rule to module creation wizard

- src/presentation/react/components/metadata-table/MetadataTable.tsx
-   **Issue:** Closes #774
- Fix showing selected item on mapping dialog
> [Fix] Show selection on mapping dialog

- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/data/metadata/MetadataD2ApiRepository.ts
- src/domain/mapping/usecases/ApplyMappingUseCase.ts
- src/domain/mapping/usecases/GenericMappingUseCase.ts
- src/utils/synchronization.ts
- Allow mapping and syncing default values
> [Feature] Allow mapping for default values

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/utils/synchronization.ts
-   **Issue:** Closes #758
- Add last 30 and 90 days options
> [Feature] Add last 30 and 90 days option

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- package.json
- src/data/custom-data/CustomDataD2ApiRepository.ts
- src/data/metadata/__tests__/integration/local-instance-mapped.spec.ts
- src/data/metadata/__tests__/integration/sync-aggregated.spec.ts
- src/data/metadata/__tests__/integration/sync-events.spec.ts
- src/domain/aggregated/types.ts
- src/domain/custom-data/entities/CustomData.ts
- src/domain/custom-data/repository/CustomDataRepository.ts
- src/domain/custom-data/usecases/GetCustomDataUseCase.ts
- src/domain/custom-data/usecases/SaveCustomDataUseCase.ts
- src/presentation/react/core/components/dropdown/Dropdown.tsx
- src/presentation/react/msf-aggregate-data/components/msf-settings-dialog/MSFSettingsDialog.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePage.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
- src/utils/analytics.ts
- yarn.lock
-   **Issue:** Closes #755
- Add years option to analytics run
https://github.com/EyeSeeTea/d2-api/pull/84
> [Feature] Add params to analytics run in MSF front-end

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- package.json
- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/data/events/EventsD2ApiRepository.ts
- src/data/metadata/MetadataD2ApiRepository.ts
- src/domain/aggregated/usecases/DeleteAggregatedUseCase.ts
- src/domain/aggregated/utils.ts
- src/domain/metadata/entities/MetadataEntities.ts
- src/domain/rules/entities/SynchronizationRule.ts
- src/presentation/react/msf-aggregate-data/components/msf-settings-dialog/MSFSettingsDialog.tsx
- src/presentation/react/msf-aggregate-data/components/org-unit-date-selector/OrgUnitDateSelector.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePage.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
- src/utils/synchronization.ts
- yarn.lock
-  **Issue:** CU-c8umqb
- Add new UI to MSFSettings
- Store minimum dates on dataStore
- Filter rules by period
- The UI does not list other minimum dates to the side
> [Feature] Add minimum date for org units

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/data/metadata/MetadataD2ApiRepository.ts
- src/domain/metadata/repositories/MetadataRepository.ts
- src/presentation/react/core/components/mapping-dialog/MappingDialog.tsx
- src/presentation/react/core/components/metadata-table/MetadataTable.tsx
> [Feature] Add show all entries filter on mapping

- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/domain/aggregated/entities/DataValue.ts
-   **Issue:** Closes CU-ck2cc5
- Pick relevant properties only
> [Fix] Pick only properties needed in analytics sync

- src/data/metadata/MetadataD2ApiRepository.ts
- src/domain/metadata/repositories/MetadataRepository.ts
- src/models/dhis/mapping.ts
- src/models/dhis/metadata.ts
- src/presentation/react/core/components/metadata-table/MetadataTable.tsx
- src/presentation/react/core/components/sync-wizard/common/MetadataSelectionStep.tsx
- src/presentation/webapp/core/pages/instance-mapping/InstanceMappingPage.tsx
- src/presentation/webapp/core/pages/manual-sync/ManualSyncPage.tsx
- src/utils/d2.ts
-   **Issue:** Closes CU-ck2ahk
- Add program indicator model to all pages
- Add program column to program indicator listing
- Add program filter to program indicator listing
> [Feature] Add program indicator model

- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/domain/aggregated/types.ts
- src/domain/mapping/usecases/GenericMappingUseCase.ts
- src/domain/synchronization/usecases/GenericSyncUseCase.ts
- src/presentation/react/core/components/sync-params-selector/SyncParamsSelector.tsx
- src/presentation/react/core/components/sync-wizard/data/AggregationStep.tsx
-   **Issue:** Closes CU-ck2gp8
- Add new toggle under instance selection
- Include zero values during analytics sync
- The zero values also have the [aggregated] comment, we can either remove it or change it to anything we want.
> [Feature] Include zero values in analytics

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/domain/aggregated/types.ts
- src/domain/aggregated/usecases/AggregatedSyncUseCase.ts
- src/domain/events/usecases/EventsSyncUseCase.ts
- src/domain/synchronization/usecases/GenericSyncUseCase.ts
- src/presentation/react/core/components/sync-params-selector/SyncParamsSelector.tsx
- src/presentation/react/core/components/sync-wizard/data/AggregationStep.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
-   **Issue:** Closes CU-cuyb7y
- Add new setting in sync rule wizard
- Exclude data values if destination value is the same as we are about to send.
> [Feature] Check if data values have the same value

- package.json
- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/presentation/react/core/components/metadata-table/MetadataTable.tsx
> [Feature] MSF Feedback

- package.json
- yarn.lock
> Release 2.7.1

- src/data/transformations/PackageTransformations.ts
-   **Issue:** Closes https://app.clickup.com/t/ff2pu0
> Fix sync dashboards with new maps

- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/data/events/EventsD2ApiRepository.ts
- src/domain/mapping/usecases/AutoMapUseCase.ts
- src/domain/mapping/usecases/GenericMappingUseCase.ts
- src/presentation/react/core/components/mapping-dialog/MappingDialog.tsx
- src/presentation/react/core/components/sync-wizard/data/AggregationStep.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePage.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
> [Feature] Final fixes for MSF release

- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
> [Fix] Remove event duplicates by id (MSF)

- .travis.yml
- package.json
- src/data/config/ConfigAppRepository.ts
- src/data/storage/StorageConstantClient.ts
- src/utils/dhisServer.ts
- https://app.clickup.com/t/fq76zq
- Default to ``dataStore``
- Disable cypress tests on travis
> [Fix] Constant storage intitialization

- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/data/events/EventsD2ApiRepository.ts
- src/data/metadata/MetadataD2ApiRepository.ts
- https://app.clickup.com/t/gz34a3
- Do not spread params on POST requests
> [Fix] Do not spread params on POST requests

- src/domain/rules/entities/SynchronizationRule.ts
- src/domain/rules/entities/__tests__/SynchronizationRule.spec.ts
- https://app.clickup.com/t/gv93h9
- Do not reset include/exclude rules on metadata change
> [Fix] Do not reset include rules

- src/presentation/webapp/core/pages/instance-list/InstanceListPage.tsx
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
> [Fix] Wait for async methods on either matches

- src/data/aggregated/AggregatedD2ApiRepository.ts
> [Fix] Chunk aggregated requests on dimensions

- src/data/transformations/__tests__/integration/helpers.ts
- src/domain/synchronization/usecases/GenericSyncUseCase.ts
> Fix integration tests

- src/data/aggregated/AggregatedD2ApiRepository.ts
- src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
> [Comment] Add Refactor TODO

- src/models/dhis/metadata.ts
> [Feature] Include program rule actions with programs

- src/utils/synchronization.ts
> [Fix] Program category option mapping from n to 1

- src/domain/events/usecases/EventsSyncUseCase.ts
- Include DE from program with analytics
> [Feature] Include DEs on analytics

- src/domain/instance/entities/Instance.ts
> [Cherry-pick] Fix mapping-this-instance

- src/models/dhis/metadata.ts
- src/presentation/react/core/components/module-wizard/common/MetadataSelectionStep.tsx
- Update dependencies of metadata models by feedback from metadata team
- Add UserGroups and RelationshipTypes to module generation wizard
> [Feature] Changes to metadata models

- src/domain/events/usecases/EventsSyncUseCase.ts
This reverts commit 3d005c6048a315bd764e64498254bc1d8872463f.
-
> Revert "Include DEs on analytics"

- src/data/events/EventsD2ApiRepository.ts
Signed-off-by: Alexis Rico <sferadev@gmail.com>
-
> [Fix] Add all fields in the events endpoint

- i18n/en.pot
- i18n/es.po
- i18n/fr.po
- i18n/pt.po
- package.json
- scripts/run.ts
- src/data/events/EventsD2ApiRepository.ts
- src/domain/aggregated/entities/DataSynchronizationParams.ts
- src/domain/events/usecases/UpdateEFHSyncRuleUseCase.tsx
- src/presentation/CompositionRoot.ts
- src/presentation/react/core/components/sync-params-selector/SyncParamsSelector.tsx
- src/presentation/react/core/components/sync-wizard/common/SummaryStep.tsx
- src/presentation/widget/pages/Root.tsx
- src/presentation/widget/pages/efh-sync-widget/EFHSyncWidget.tsx
- src/presentation/widget/pages/efh-sync-widget/SyncRuleButton.tsx
- yarn.lock
-   **Issue:** Closes https://app.clickup.com/t/2zpym5j
- Added new widget: efh-sync
```
$ yarn start efh-sync
```
> Add EFH Sync widget

- scripts/run.ts
-   **Issue:** Closes [Install multiple metadata sync flavours](https://app.clickup.com/t/8694jx82y)
- CU-8694jx82y 
Add function to define namespace.
> feat: add function to set namespaces

- src/domain/metadata/utils.ts
- src/presentation/webapp/WebApp.tsx
-   **Issue:** Closes https://app.clickup.com/t/8694rk79p
#8694rk79p
> remove sharing objects

- src/domain/synchronization/entities/SynchronizationBuilder.ts
-   **Issue:** Closes https://app.clickup.com/t/86953yqac
> update initial value for allTEIs parameter

- src/data/instance/InstanceD2ApiRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/8694z90en
https://github.com/EyeSeeTea/metadata-synchronization/assets/37223065/2afc9d8e-a9c6-42ce-bd79-6f14806cddfa
#8694z90en
> bugfix: refresh ui on deleting an instance

- package.json
- src/domain/entities/EmergencyResponses.ts
- src/presentation/webapp/sp-emergency-responses/EmergencyResponsesSyncHomePage.tsx
-   **Issue:** Closes https://app.clickup.com/t/8697u4thh
> [EFH] Offline v40

- .github/workflows/main.yml
> Fix github action

- src/data/metadata/MetadataD2ApiRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/8698a68qy
- Merging this PR with Development in this PR https://github.com/EyeSeeTea/metadata-synchronization/pull/968 I detected an error to retrieve related user of a category.
The error consist in an error 500 to retrieve a non existed user even to retrieve using the users endpoint https://dev.eyeseetea.com/who-dev-41/api/users/s5EVHUwoFKu
The error that appear in the sync summary is confused, I changed the error to clarify that the error is to retrieve metadata by Ids and I specify the ids.
Previously
Now
> Clarify in the error when it's requesting metadata
