EyeSeeTea/metadata-synchronization

i18n/en.pot
src/components/app/Root.jsx
src/components/instance-configurator/InstanceConfigurator.jsx
src/components/instance-form-builder/GeneralInfoForm.jsx
src/models/instance.ts

* **Issue:** Closes #33 
Connection validation is no longer performed on save. There is now a separate button on the form to validate the connection as well as a new contextual action on the instancesList. 
This branch is based off the `encrypt-password-7` in order to integrate encryption into the connection validation. Same warnings as that branch, `app-config.json` file must be created and older instances created before this PR will break the app when trying to `Edit` or `Test Connection` from the contextual options

Add separate button to test connection as well as contextual action

---

i18n/en.pot
src/components/app/App.jsx
src/components/sync-configurator/BaseSyncConfigurator.jsx
src/components/sync-dialog/SyncDialog.jsx
src/logic/synchronization.ts
src/models/dataStore.ts
src/models/instance.ts
src/themes/dhis2-legacy.theme.js
src/themes/dhis2.theme.js
src/types/synchronization.d.ts
src/utils/testing.js

* **Issue:** Closes #40 
- Add LoadingProvider to the root app.
- Add a new SyncDialog that handles the synchronization state.
- Allow getting data by id from dataStore.
- Add a summary to the SyncDialog of the metadata objects (we need to decide how to output or if we leave this for Milestone 2).
- Verify extreme cases, no instances selected, no metadata selected and add message through snackbar.
- https://github.com/EyeSeeTea/d2-ui-components/pull/20
- https://github.com/EyeSeeTea/d2-ui-components/pull/23
- Do not merge until d2-ui-components is published and package.json is updated.
- The branch depends on other branches that are not ready to merge either.

Implement basic instance selection dialog

---

i18n/en.pot
src/components/shared/Dropdown.jsx
src/components/sync-configurator/BaseSyncConfigurator.jsx
src/components/sync-summary/SyncSummary.jsx
src/logic/synchronization.ts
src/types/synchronization.d.ts
src/utils/d2.ts
src/utils/synchronization.ts

* **Issue:** Closes #42 
- Added the main logic from the import-export-app for reporting.
- Improved the import-export-app UI into material-ui tables.
- Collapsed all when more than one instance involved.
- Solved "Warning contextType"
- Solved "Network error causing to finish sync"
- Solved "Dropdown label was not defined"
- The two tables generated might be combined later into a parametric single method.
- History page (logger) should be moved from #42 into its own card

Sync Summary Details

---

i18n/en.pot
src/components/shared/Dropdown.jsx
src/components/sync-configurator/OrganisationUnitSync.jsx
src/models/d2Model.ts
src/types/d2-ui-components.d.ts

* **Issue:** Closes #59 
- Improve OU Group filter by adding indirect access to d2Model
- Add OU Level filter re-using the new OU Group filter logic
- Improve the listMethod to customize on-demand the fields/filters/paging required
- We had a bug where only 50 OU Groups appeared in the dropdown because paging was not set to false.

Add OU Level Filter and improve OU Group Filter

---

src/models/d2Model.ts
src/types/d2-ui-components.d.ts

- This can be tested with https://github.com/EyeSeeTea/d2-ui-components/pull/34
- If fields are explicitly required as a filter do not internally compute the fields to use.
- This way if we only need to get "ids" we can do smaller requests to DHIS2 directly by overriding the fields array.

Add a property to override the fields in list()

---

public/index.html

Error: "Cannot read property feedbackDhis2 of undefined"
- `index.html` loaded jquery with `http://`, let's use `//` (same protocol)
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
Note that this will be a problem if we need syncs to/from dhis2 instances on http from the app in a https instance.

￼Use same protocol for jquery load

---

.travis.yml
cypress.json
cypress/integration/instance-configurator.spec.js
cypress/integration/landing-page.spec.js
cypress/support/commands.js
cypress/support/network-fixtures.js
cypress/support/utils.js
package.json
src/components/instance-form-builder/GeneralInfoForm.jsx
src/components/shared/PageHeader.jsx
src/index.js
yarn.lock

- Wait-on module has a false-positive with webpack-dev-server. Instead of waiting for http, we now wait for http-get. See https://github.com/bahmutov/start-server-and-test/blob/master/README.md#note-for-webpack-dev-server-users
- REACT_APP_CYPRESS=true was not set during server boot.
- We had a problem that randomly travis crashed because 10s was not enough for server to boot, this is now fixed with the wait-on.
- Though this won't fix the issues we're having with cypress yet but it will likely make the travis testing more robust.

Add Integration tests for Instance creation and metadata synchronization & Update travis config to actually wait for server to load

---

.travis.yml
i18n/en.pot
src/components/notifications-table/NotificationsTable.jsx
src/components/sync-dialog/SyncDialog.jsx
src/logic/synchronization.ts
src/models/d2Model.ts
src/models/dataStore.ts
src/models/instance.ts
src/models/syncReport.ts
src/types/synchronization.d.ts
src/utils/synchronization.ts

* **Issue:** Closes #86 
- Transform synchronization into a state machine with generator
- Update loading page with messages
- Add a visited id dictionary and move recursive function to a inner method
- Add missing TS definitions for arrow methods
- Previous algorithm took linear time
- Current algorithm takes logarithmic time
- For detailed comparison see https://github.com/EyeSeeTea/metadata-synchronization/issues/86#issuecomment-495881754

Improve performance on metadata synchronization

---

src/components/synchronization-page/OrganisationUnitPage.jsx
src/models/d2Model.ts
src/models/d2ModelFactory.ts

- Re-use our powerful core logic for dependency fetching
- Re-use the new abstracted Metadata Table from Sync Rules
- This is more difficult to test but the resulting metadata package seems to be correct

Allow synchronization of OrganisationUnitGroupSets

---

i18n/en.pot
src/components/history-list-page/HistoryPage.jsx
src/components/rules-creation-page/steps/InstanceSelectionStep.jsx
src/components/rules-list-page/SyncRulesPage.jsx
src/logic/synchronization.ts
src/models/dataStore.ts
src/models/syncReport.ts
src/models/syncRule.ts
src/types/synchronization.d.ts

* **Issue:** Closes #113 
- Add support for ```paging=false``` in dataStore getPaginatedData()
- Add syncRule id to a syncReport if the sync was executed as part of a rule
- Show the syncRule in the Notifications page
- https://github.com/EyeSeeTea/d2-ui-components/pull/50

[History] Visualize if a sync was executed by a rule

---

i18n/en.pot
src/components/rules-creation-page/SyncRulesWizard.jsx
src/components/rules-creation-page/steps/GeneralInfoStep.jsx
src/components/rules-creation-page/steps/SaveStep.jsx
src/components/rules-creation-page/steps/SchedulerStep.jsx
src/components/rules-list-page/SyncRulesPage.jsx
src/index.js
src/models/syncRule.ts
src/types/synchronization.d.ts
src/utils/apiTranslations.js
src/utils/validCronExpression.js
src/utils/validations.js

* **Issue:** Closes #112 
* This PR adds the basic functionality to stop blocking Phase 2 development
* UI/UX improvements should be implemented in upcoming PRs (example #131)
- Add new scheduling step to Sync Rules Wizard
- Fix general info step to be fully immutable
- Add validation before saving on Wizard
- Add new columns to Sync Rules Page to reflect scheduling
- Add cron expressions validation from @dhis2/scheduler-app
- Since we are using the dataStore as database and we are unable to store booleans, we do the string conversion on the model.

[Scheduler] Add new scheduler to Sync Rules

---

i18n/en.pot
package.json
src/components/rules-creation-page/steps/SaveStep.jsx
src/components/rules-creation-page/steps/SchedulerStep.jsx
src/components/rules-list-page/SyncRulesPage.jsx
yarn.lock

- In the sync rules wizard, when inserting a valid cron expression, we previsualize the result. If it's incorrect we have the default "Select frequency" placeholder.
- We should probably update the options we suggest in the dropdown to match the same auto generated string (but I guess we should think before which cron expressions are useful to the clients ie: Every day at 11PM from Monday to Friday)
- The library supports multiple locales, not sure if we want to enable that feature yet (they support more languages than us and could lead to mixed translations UI)
- Added as string interpolation, also tested adding tooltips but not sure what's the best approach.

[Scheduler] User friendly cron expressions

---

i18n/en.pot
src/components/app/App.jsx
src/components/app/Root.jsx
src/components/dropdown/Dropdown.jsx
src/components/landing-page/LandingPage.jsx
src/components/metadata-table/MetadataTable.jsx
src/components/rules-creation-page/steps/SaveStep.jsx
src/components/sync-dialog/SyncDialog.jsx
src/components/synchronization-page/DeletedObjectsPage.jsx
src/components/synchronization-page/GenericSynchronizationPage.jsx
src/logic/delete.ts
src/logic/metadata.ts
src/logic/synchronization.ts
src/models/dataStore.ts
src/models/deletedObjects.ts
src/models/instance.ts
src/types/d2.d.ts
src/utils/d2.ts
src/utils/synchronization.ts

* **Issue:** Closes #100 
* **Depends on:** https://github.com/EyeSeeTea/d2-ui-components/pull/57
- Add a new SyncPage that hosts all the deleted objects of the instance
- Before asking to delete the objects on destination, we query destination to see if they still exists
- We have re-used as much code as possible, everything works with the same Generic Sync Page that we use for programmatic metadata synchronizations.
- Deletion is not a fully working feature of DHIS2, for example it will fail if you are deleting an organisation that has children or if you are deleting an object that has been re-created with the same id after being deleted.

Deleted objects

---

i18n/en.pot
package.json
src/components/app/App.jsx
src/components/app/Root.jsx
src/components/instance-list-page/InstancesPage.jsx
src/components/rules-list-page/SyncRulesPage.jsx
src/components/sharing-dialog/Access.jsx
src/components/sharing-dialog/AutoComplete.jsx
src/components/sharing-dialog/PermissionOption.jsx
src/components/sharing-dialog/PermissionPicker.jsx
src/components/sharing-dialog/Sharing.jsx
src/components/sharing-dialog/SharingDialog.jsx
src/components/sharing-dialog/UserSearch.jsx
src/components/sharing-dialog/utils.js
src/components/synchronization-page/GenericSynchronizationPage.jsx
src/models/instance.ts
src/models/syncRule.ts
src/types/d2.d.ts
src/types/modules.d.ts
src/types/synchronization.d.ts
src/utils/permissions.ts
yarn.lock

* **Issue:** Closes #148 
- Visual component for Sharing settings
- Add ``downshift`` dependency
- Import Sharing component from d2-ui
- Remove old ``d2.i18n`` code, ``recompose`` library and logic coupling inside the components
- Expose the logic methods as props in the components to make them agnostic (allowing dataStore support)
- Administrative user roles
- On application load it checks if the user role exists and creates it if negative
- For creation of sync rules and/or instances we verify user has the administrative role
- Sharing settings and user access
- For ``SyncRule.list`` we filter the results with the ones the user has access (read)
- For contextual actions (edit, delete, sharing settings, toggle enabled) we verify user has access (write)
- We support public access rules …

Sharing settings and administrative user role

---

i18n/en.pot
package.json
src/components/app/App.jsx
src/components/app/Root.jsx
src/components/instance-list-page/InstancesPage.jsx
src/components/rules-creation-page/steps/MetadataSelectionStep.jsx
src/components/rules-list-page/SyncRulesPage.jsx
src/components/sharing-dialog/Access.jsx
src/components/sharing-dialog/AutoComplete.jsx
src/components/sharing-dialog/PermissionOption.jsx
src/components/sharing-dialog/PermissionPicker.jsx
src/components/sharing-dialog/Sharing.jsx
src/components/sharing-dialog/SharingDialog.jsx
src/components/sharing-dialog/UserSearch.jsx
src/components/sharing-dialog/utils.js
src/components/synchronization-page/GenericSynchronizationPage.jsx
src/models/d2Model.ts
src/models/syncRule.ts
src/types/d2.d.ts
src/types/modules.d.ts
src/types/synchronization.d.ts
src/utils/permissions.ts
yarn.lock

* **Issue:** Closes #149 
* I am still testing this PR but uploading for @adrianq to also begin with the testing
- Program Indicators: Followed the same as per Indicators. The main difference is ```analyticsPeriodBoundaries``` but the object appears to be bundled inside.
- Program Indicator Groups: Followed the same as per Indicator Groups.
- Program Rules: Has a very strong relationship with ``program`` and I find dangerous synchronizing this metadata without controlling the element exists on remote.
- Program Rule variable: Has a very strong relationship with ``program``. ``programStage`` and ``dataElement``. This appears to be a dangerous uncontrolled operation.
For future versions of metadata-sync (or data-sync) we could try to automate the verification of some of these relationships …

Add new metadata types for programs

---

i18n/en.pot
package.json
src/components/rules-creation-page/steps/GeneralInfoStep.jsx
src/components/rules-creation-page/steps/SaveStep.jsx
src/models/syncRule.ts
src/types/synchronization.d.ts
yarn.lock

* **Issue:** Closes #173
- Add code, user, created, lastUpdated, lastUpdatedBy properties
- Allow introducing code in the sync rules wizard
- Allow read/write access to the user who created a given sync rule.
- Remember that even if the user created the sync rule, if he/she does not have EXECUTION authority will be unable to execute the rule.
- To maintain backwards compatibility we are checking if the ``user`` property exist even if it is mandatory to be non-null as per the type. @tokland Do you have a better approach on this?

Allow sync rule owners

---

src/models/d2Model.ts

* **Issue:** Closes #198 
- Remove the exact time in the filter that goes into the query.
See the network requests.
Before:
```
http://taris.sferadev.com:9004/api/dataElements?filter=lastUpdated:ge:2019-10-26T08:56:00.000Z&fields=id&page=1&pageSize=20&order=name%3Aiasc&paging=false
```
After:
```
http://taris.sferadev.com:9004/api/dataElements?filter=lastUpdated:ge:2019-10-26&fields=id&page=1&pageSize=20&order=name%3Aiasc&paging=false
```
[Last updated date filter set time to 00:00](https://app.gitkraken.com/glo/board/XaBKjXlqfAAPh4Tg/card/XbrZCRz3OwAPE_BZ)

Remove time from lastUpdated query to d2Model

---

i18n/en.pot
src/components/sync-summary/SyncSummary.jsx
src/logic/sync/aggregated.ts
src/logic/sync/events.ts
src/logic/sync/generic.ts
src/logic/sync/metadata.ts
src/models/syncReport.ts
src/types/synchronization.d.ts
src/utils/synchronization.ts

* **Issue:** Closes #242 
* **Issue:** Closes #243  
* **Issue:** Closes #244  
* **Issue:** Closes #246  
- Generate data statistics during synchronization
- Show a new "Data Statistics" section in the Sync Summary component
- Tooltip becomes available when there are more than 3 org units provided

[Feature] Add data statistics to sync report

---

i18n/en.pot
src/components/sync-wizard/Steps.ts
src/components/sync-wizard/common/SummaryStep.jsx
src/components/sync-wizard/data/EventsSelectionStep.tsx
src/components/sync-wizard/data/PeriodSelectionStep.tsx
src/models/syncRule.ts
src/types/synchronization.d.ts
src/utils/synchronization.ts

* **Issue:** Closes #239 
- Add dropdown in "Period" step for both aggregated and events
- Calculate startDate and endDate from the dropdown selection
- Delegate filtering to DHIS2 api endpoints
- We can verify that the dates are correctly calculated in the network call (we are not doing any kind of filtering in the app).

[Feature] Allow relative periods for data sync

---

i18n/en.pot
src/components/sync-wizard/Steps.ts
src/components/sync-wizard/common/MetadataSelectionStep.tsx
src/components/sync-wizard/data/CategoryOptionsSelectionStep.tsx
src/components/sync-wizard/data/EventsSelectionStep.tsx
src/components/sync-wizard/data/OrganisationUnitsSelectionStep.tsx
src/components/sync-wizard/data/PeriodSelectionStep.tsx
src/models/syncRule.ts
src/types/synchronization.d.ts
src/utils/synchronization.ts

* **Issue:** Closes #171 
- Add new Category Option Selection Step
- As discussed, for simplicity we are only filtering "attributeCategoryOption" for now.
- Also as discussed, not yet implemented for events as it requires to gather feedback from client and understand the real needs.
- In the network tab we can validate that filtering is applied (example dataset: Drug distribution HMO23)
- Since category option combos name is not unique, we have the following as name ``Display Name (UID)``.

[Feature] Add attribute category option step

---

src/pages/history/HistoryPage.tsx

* **Issue:** Closes #274 
- Clear selection after delete
Steps to reproduce bug:
- Select one item in any History page
- Delete the history entry
- Selection is still available in other pages

[Bugfix] Clear selection on delete history page

---

i18n/en.pot
src/models/instance.ts
src/models/syncRule.ts
src/pages/history/HistoryPage.tsx
src/pages/instance-creation/InstanceCreationPage.jsx
src/pages/instance-list/InstanceListPage.jsx
src/pages/sync-rules-creation/SyncRulesCreationPage.tsx
src/pages/sync-rules-list/SyncRulesListPage.jsx

* **Issue:** Works in #289 
- Add replicate contextual action to "SyncRules" and "Instances"
- Update default action in "Instances" page
- Update default action in "History" page

Add replicate and update default table actions

---

src/components/sync-wizard/common/SummaryStep.jsx
src/components/sync-wizard/data/PeriodSelectionStep.tsx
src/types/synchronization.d.ts
src/utils/synchronization.ts

* **Issue:** Work #289 
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/28
* **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/29
- Added more verbose periods
- **IMPORTANT**: I have removed the "last 6 months" and "this 6 months" options. MomentJS [does not have that periodicity](https://github.com/moment/moment/pull/1998) and it is not trivial to implement a solution bypassing MomentJS. If we deem necessary to have it we might discuss what rules could calculate the current half of the year and/or past half of the year without the library and maintaining valid dates.
I have executed a test method locally and returned this matrix for today.
```
[
{
"period": "ALL",
"value": [
"1970-01-01",
"2030-12-31"
]
},
{ …
```

Add more relative periods

---

i18n/en.pot
src/components/sync-wizard/common/SummaryStep.jsx
src/utils/synchronization.ts

* **Issue:** Closes #284 
- Add organisation units, category options and events to ``SummaryStep``

[Feature] Add missing properties in wizard's summary step

---

.travis.yml
cypress/integration/manual-metadata-sync.spec.js
cypress/integration/metadata-sync-rule-edit.spec.js
cypress/integration/metadata-sync-rule-new.spec.js
cypress/support/commands.js
cypress/support/page-objects/ManualMetadataSyncPageObject.js
cypress/support/page-objects/common/SyncRuleDetailPageObject.js
package.json
src/models/__tests__/syncRule.spec.ts
src/models/d2Model.ts
src/models/d2ModelFactory.ts
yarn.lock

* **Issue:** Closes #415 
- I have added the Dashboard model to metadata models 
- I have added the UserGroup model to metadata models
- I have added the DataSet model to metadata models
- I have created new tests
The sync process fails if the dashboards contain related metadata as org units and this metadata does not exist in the target instance.
The sync process fails if the dashboards contain related metadata as org units and this metadata does not exist in the target instance.
User roles can not be synced directly with UserGroup and users because roles are embedded under UserCredentials and current data sync logic not found user roles to add it in the package to upload.
A possible solution is to add the UserRole model to metadata models and sync it previously, another is created …

Add new metadata objects

---

src/models/d2Model.ts

* **Issue:** Closes #
After testing with new servers build I have verified that metadata endpoint now returns indicatorGroupSets relationships for an indicatorGroup. Then I have modified include rules to the plural and now is indicators sync is working.

Fix indicator model group set

---

i18n/en.pot
i18n/es.po
i18n/fr.po
i18n/pt.po
src/presentation/webapp/components/migrations/Migrations.tsx

- When running on development (localhost:8081), if the dataStore is more up-to-date than the running application allow the developer to continue to the app anyway.
- On production the behavior is the same as always, error telling the application cannot be started

[Feature] Allow bypassing migrations on development builds

---

src/data/metadata/MetadataD2ApiRepository.ts
src/presentation/webapp/components/metadata-table/MetadataTable.tsx
src/utils/pagination.ts

-   **Issue:** Closes #250 
- On `MetadataD2ApiRepository` there were 2 methods affected: `listMetadata` and `listAllMetadata`. I've added two new wrapper methods (`getListAll`, `getListPaginated`) that check the length of the filter `id->in:[ids]` and, if greater than a max value (500): 1) split the list, 2) perform N requests, 3) join the objects, 4) sort the objects (in both cases, api/manual), 4) paginate them (if needed)
- While testing, I noticed that the current page was not reset when filters changed. I don't know if that was the indented behaviour, but I found it problematic, at least for the "only selected items" so I force a `page: 1` for that filter. @SferaDev, can you confirm? Do we need this for the other filters? https://github.com/EyeSeeTea/metadata-synchronization/pull/575 …

[Fix] Workaround 414-uri too long

---

src/presentation/webapp/pages/instance-list/InstanceListPage.tsx
src/presentation/webapp/pages/manual-sync/ManualSyncPage.tsx

-   **Issue:** Closes https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/72
- Clear selection in two different pages

[Fix] Clear selection in two different tables

---

package.json
src/data/aggregated/AggregatedD2ApiRepository.ts
src/domain/metadata/utils.ts
src/models/syncRule.ts
src/presentation/webapp/components/sync-wizard/SyncWizard.tsx
src/presentation/webapp/components/sync-wizard/common/GeneralInfoStep.tsx
src/presentation/webapp/components/sync-wizard/common/SummaryStep.jsx
src/presentation/webapp/pages/sync-rules-list/SyncRulesListPage.tsx
src/utils/old-validations.ts

- Add back ``dataSetElements`` to ``dataSet`` during metadata sync
- Do not hang-up if user does not have permissions to retrieve dataValues
- Fix cosmetic bug editing name or description of a sync rule

[Fix] Bugs found after release

---

src/models/dhis/metadata.ts

- We were removing the program relationship of program indicators as an exclude rule

[Fix] Do not remove program relationship of a program indicator

---

package.json
src/data/events/EventsD2ApiRepository.ts
src/data/metadata/__tests__/integration/sync-events.spec.ts
src/presentation/react/components/sync-wizard/data/EventsSelectionStep.tsx

- Improve performance of ``EventsSelectionStep``
- Paginate over ``events`` endpoint while querying the API
- Add a comment on code on ``EventsRepository`` about the design choices
- If user selects specific events do not query all events, instead ask the API for the ids

[Fix] Paginate over events endpoint

---

src/presentation/react/components/package-list-table/PackageListTable.tsx

-   **Issue:** Closes #705
- The source package was already showing in the sync summary, but it was only assigned from the package import wizard, but not from the normal import.
- Now it is also assigned from normal import.

Fix bug origin package not assigned from normal import

---

package.json
src/presentation/react/components/module-list-table/ModuleListTable.tsx
yarn.lock

-   **Issue:** Closes #760
We use the same package object generated in the dialog to save the package in the different versions, then we need to generate a new uid for every package to save. This uid generation can not be realized in the CreatePackageUseCase because we would be modifying the created object from the outside and this a potential problem in other parts of the application.
The uid modification must be in the presentation layer.

Fix bug generating multiple package versions

---

src/presentation/react/core/components/mapping-dialog/MappingDialog.tsx

-   **Issue:** Closes https://app.clickup.com/t/cpw49m

Fix mapping dialog if previously  program has been mapped

---

package.json
src/data/aggregated/AggregatedD2ApiRepository.ts
src/data/metadata/__tests__/integration/local-instance-mapped.spec.ts
src/data/metadata/__tests__/integration/sync-aggregated.spec.ts
src/data/storage/StorageConstantClient.ts
src/domain/mapping/usecases/GenericMappingUseCase.ts
src/presentation/webapp/core/pages/instance-list/InstanceListPage.tsx
src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts

- https://app.clickup.com/t/gv5y9c
- https://app.clickup.com/t/gv5xwt
- Do not ask for all fields on each network call
- Give more priority to ``aggregateExportCategoryOptionCombo``
- The issue was that we queried the ``description`` field always which has huge stringified objects

[Fix] Feedback from MSF

---

i18n/en.pot
i18n/es.po
i18n/fr.po
i18n/pt.po
src/data/aggregated/AggregatedD2ApiRepository.ts
src/data/metadata/MetadataD2ApiRepository.ts
src/data/reports/ReportsD2ApiRepository.ts
src/data/storage/StorageConstantClient.ts
src/domain/aggregated/usecases/AggregatedSyncUseCase.ts
src/domain/aggregated/utils.ts
src/domain/reports/entities/SynchronizationReport.ts
src/domain/reports/entities/SynchronizationResult.ts
src/domain/reports/repositories/ReportsRepository.ts
src/domain/reports/usecases/CleanSyncReporstUseCase.ts
src/domain/storage/repositories/StorageClient.ts
src/presentation/CompositionRoot.ts
src/presentation/react/core/components/sync-summary/SyncSummary.tsx
src/presentation/webapp/msf-aggregate-data/pages/MSFHomePage.tsx
src/presentation/webapp/msf-aggregate-data/pages/MSFHomePagePresenter.ts
src/types/d2-api.ts
src/utils/common.ts

For a map of relationships (child -> parent[]), return the minimum array of parents that include all of the children. 
Code used for: dataElements->dataElementGroups and dataElements->dataSets
Implementation: Invert the original relationship to parent -> child[], and, for every iteration until all children are seen, sort the pairs by length of children, and update the relationship accordingly.

Reduce dataElementGroups/dataSets to getAggregated call

---

src/data/migrations/client/MigrationsRunner.ts

- https://github.com/EyeSeeTea/Bulk-Load/pull/223
- With the change introduced to remove the dialog on fresh install we are false detecting other situations (like before migrations was introduced but storage already existed)

[Fix] Initialize correctly migrations

---

src/presentation/react/core/components/sync-wizard/common/MetadataSelectionStep.tsx

-   **Issue:** Closes https://app.clickup.com/t/1h7vu1x
The problem was the MetadataSelectionStep observe changes in the sync rule object when a change occurs in this object then retrieve the instance and update the state again. This provokes a re-render in the metadata table by the new remote instance object, and this occurs when any prop in the sync rule change as the selected metadata. The metadata table component observes changes in the remote instance prop and then refresh the filters assigning page 1.
The solution is to observe in the MetadataSelectionStep changes in the sync rule but only for the needed property in the useEffect, originInstance in this case, this avoids unnecessary rerender in MetadataTable.
-   Any change in the [GUI …

Sync rule metadata step - Fix back to page 1 after select item on page 2

---

src/data/transformations/PackageTransformations.ts

-   **Issue:** Closes https://app.clickup.com/t/24xgpdf
These visualization bugs exist on 2.34 also because columnDimensions and fixed periods has not changed between 2.34 and 2.36
Create a visualization and add it to a new dashboard. Sync the dashboard between 2.36 instances and the sync should work and the visualization should be created successfully in the destination

Fix bugs syncing visualizations in 2.36

---

i18n/en.pot
i18n/es.po
i18n/fr.po
i18n/pt.po
src/data/events/EventsD2ApiRepository.ts
src/domain/aggregated/entities/DataSynchronizationParams.ts
src/presentation/react/core/components/sync-params-selector/SyncParamsSelector.tsx
src/presentation/react/core/components/sync-wizard/common/SummaryStep.tsx

https://app.clickup.com/t/3banacm
I have added a setting for  the event synchronization to change the sync/async mode.
This feature was required to sync events from 2.35 to 2.36
-
to test you should create manual/rule sync with async mode on and off, and check the post endpoint in network.

added sync/async mode for events

---

src/data/metadata/MetadataD2ApiRepository.ts
src/presentation/react/core/components/sync-wizard/common/SummaryStep.tsx
src/utils/d2-utils.ts

-   **Issue:** Closes https://app.clickup.com/t/86947bw20
The `/api/metadata` endpoint returns 3 different types of results when you pass an event report id: `eventReports`, `eventCharts` and `eventVisualizations`.
which causes duplicating metadata results when you want to create a sync rule:
~In order to avoid this after getting the metadata information I'm doing an extra request to the `eventReports/eventCharts` endpoint to determine where these metadata really belongs.~
**UPDATE:** @MiquelAdell  Instead doing an extra request I'm using the type attribute since `EventReports` only could be of type:  `PIVOT_TABLE` or `LINE_LIST`
Also, since we don't have support for `eventVisualizations` in d2-api I'm ignoring this kind of metadata.
Event Reports …

fix create sync rule for event charts and reports

---

src/presentation/webapp/WebApp.tsx

-   **Issue:** Closes https://app.clickup.com/t/8694rz1mc
[MetaData-Synchronization_reload_bug.webm](https://github.com/EyeSeeTea/metadata-synchronization/assets/461124/01cf5097-d8b4-48d9-b06e-22326c7f50ff)
8694rz1mc

avoid reloading app after loading feedback component

---

package.json
yarn.lock

-   **Issue:** Closes #? partial : https://app.clickup.com/t/8694w3grg, #8694w3grg
Fix Scheduler build.
-
run `yarn build-scheduler` - a zip should be generated successfully.

fix: fixing scheduler build

---

src/data/common/D2ApiDataStore.ts
src/data/data-store/DataStoreMetadataD2Repository.ts
src/data/metadata/MetadataD2ApiRepository.ts
src/data/storage/StorageDataStoreClient.ts
src/domain/common/entities/Struct.ts
src/domain/common/factories/RepositoryFactory.ts
src/domain/data-store/DataStoreMetadata.ts
src/domain/data-store/DataStoreMetadataRepository.ts
src/domain/metadata/entities/MetadataEntities.ts
src/domain/metadata/usecases/MetadataSyncUseCase.ts
src/domain/packages/entities/MetadataPackageDiff.ts
src/domain/reports/entities/Stats.ts
src/domain/synchronization/usecases/GenericSyncUseCase.ts
src/models/dhis/factory.ts
src/models/dhis/metadata.ts
src/presentation/CompositionRoot.ts
src/presentation/react/core/components/metadata-table/MetadataTable.tsx
src/presentation/react/core/components/sync-wizard/common/MetadataSelectionStep.tsx
src/presentation/react/core/components/sync-wizard/common/SummaryStep.tsx
src/presentation/webapp/core/pages/manual-sync/ManualSyncPage.tsx

-   **Issue:** Closes https://app.clickup.com/t/8694jg0zj
[MetaData-Synchronization_keys (1).webm](https://github.com/user-attachments/assets/aac4ed78-780c-4b4c-a92f-af032ed68ddf)
**Executing rule/ Summary Results**
[MetaData-Synchronization_datastore_and_metadata.webm](https://github.com/user-attachments/assets/7d29ca9c-c25c-49df-b3df-b1202b6b65b9)
**DataStore in summary step**
**select individual keys**
- DHIS2 does not support pagination for namespaces so I'm always adding all of them in one page.
- Since the API does not support processing everything in a single transaction, there might be cases where part of the data is processed, but another part is not (closing the browser before finishing the execution, destination server not being available, etc).

add dataStore support

---

src/data/transformations/PackageTransformations.ts
src/presentation/react/core/components/module-list-table/NewPackageDialog.tsx

-   **Issue:** Closes https://app.clickup.com/t/8696arbge #8696arbge

Support to 2.41

---

src/domain/aggregated/entities/DataSynchronizationParams.ts
src/domain/synchronization/usecases/GenericSyncUseCase.ts

-   **Issue:** Closes #869847mre [Events do not get synced if period is "Since last successful"](https://app.clickup.com/t/869847mre)
- Fix comparing dates both in ISO when filtering events if period is `SINCE_LAST_SUCCESSFUL_SYNC`
1. Create an event sync rule with period since "last successful execution"
2. Execute sync rule
3. Create an event in the program during same hour
4. Execute and check that event was sync

Events do not get synced if period is "Since last successful"

---

src/data/events/EventsD2ApiRepository.ts
src/data/tracked-entity-instances/TEID2ApiRepository.ts
src/domain/events/usecases/EventsSyncUseCase.ts
src/domain/reports/entities/SynchronizationResult.ts

-   **Issue:** Closes #8699bn9tq [Metadata Sync - Debug & Resolve Issues for Setup](https://app.clickup.com/t/8699bn9tq)
- Show also tei sync report if rule has any TEI selected
- Fix error with `orgUnitPath`: Send only allowed params when POST TEIs
- Show also tei sync report if rule has any TEI selected
BEFORE:
AFTER:
- Fix error with `orgUnitPath`: Send only allowed params when POST TEIs
BEFORE:
AFTER:

Fix: Show also tei sync report if rule has any TEI selected
